### ISSUE TITLE
Detekcija i rešavanje CAPTCHA-i na web formama

### ISSUE THREAD

**Issue by acastef** [ftn-ai-lab/sc-2018-siit#10]
- Tim čine:
	1. Aleksandar Stefanović, index:  sw3-2015
	2. Danijel Radaković, index:  sw11-2015

- Definicija problema:

	Problem koji ćemo rešavati je rešavanje CAPTCHA-i na web formama. Cilj je da se sa formi na kojima se nalazi više CAPTCHA obrazaca pronađu svi obrasci, a zatim i da se sve pronađene CAPTCHA-e prevedu na tekst koji se nalazi na samom obrascu. CAPTCHA obrasci će biti fiksne dimenzije,  jer bi problem postao mnogo komplikovaniji ukoliko su obrasci promenljivih dimenzija, ali ćemo pokušati da rešimo i varijantu sa promenljivim dimenzijama. Takođe, CAPTCHA obrasci će se nalaziti na različitim pozicijama na formi. Zatim, svaki CAPTCHA obrazac će se sastojati od proizvoljnog broja karaktera koji treba da se prepoznaju, i to u redosledu u kojem se nalaze na svakom obrascu pojedinačno. 

- Motivacija rešenja:
	Primena ovog rešenja bi se mogla naći u tome što bi mogli da se naprave botovi koji rešavaju ovaj problem, jer se CAPTCHA javlja u dosta situacija kod kojih žeilimo da se prijavimo na neku društvenu mrežu, da se napravi neki nalog na bilo kom sajtu, a da bismo to uradili prvo moramo svojim okom da raspoznamo šta znači zadati iskrivljeni i nejasan tekst i da ga unesemo u neko polje, kako bi sistem odlučio da li smo dobro protumačili CAPTCHA-u ili ne. Ponekad je taj tekst veoma malo čitljiv, i postoji problem da se raspozna. Zato smatramo da bi naše rešenje moglo da pomogne korisnicima u rešavanju ovog problema. 

- Skup podataka:
	Ručno pravljen skup podataka.

- Metodologija:
	Problem se sastoji iz 2 celine, otkrivanje regiona na kojima se nalazi CAPTCHA, i rešavanje pronađenih CAPTCHA-i. Za prvu celinu ce biti potrebna lokalizacija objekata, za koju ćemo koristiti R-CNN, i kao rezultat bi trebao da vrati pozicije na kojima se nalaze sve CAPTCHA-e na formi.  Za rešavanje druge celine smo se odlučili za korišćenje konvolutivne neuronske mreže, koja će nam izvršit ekstrakciju feature-a, a dobijene feature-e ćemo koristiti kao ulaz u rekurentnu neuronksu mrežu (LSTM) kako bismo izvršili propagaciju informacija, tj dobijali krajnje rešenje problema.

- Evaluacija

        Za evaluaciju detekcije CAPTCHA-i ćemo koristiti IOU, a evaluaciju rešavanja CAPTCHA-i ćemo vršiti empirijski.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by acastef** [comment]
U komentaru ostavljam link na repozitorijum.
https://github.com/acastef/CaptchaResolver
