### ISSUE TITLE
Virtuelni kontroler za igrice

### ISSUE THREAD

**Issue by tarjantamas** [ftn-ai-lab/sc-2018-siit#11]
**Tim**
- Nikola Zeljković SW1-2015
- Sara Šuković SW4-2015
- Tamaš Tarjan SW6-2015

**Definicija problema**
- Problem koji rešavamo je detekcija određenih ručnih i telesnih pokreta sa kojim je moguće kontrolisati vozila i karaktere u određenim igricama.

**Motivacija rešenja**
- Sa ovim 'virtuelnim kontrolerom' moguće je voziti automobile i kamione u igricama poput Euro Truck Simulator 2, GTA V, itd... uz pomoć malo kvalitetnije web kamere ili kamere sa android telefona. Sa ovim 'virtuelnim kontrolerom' korisnik može da izbegne kupovinu skupljih specijalizovanih kontrolera.

**Skup podataka**
- Ručno pravimo skup podataka kao i pipeline za outsourcing podataka koji može da se upotrebi za dodatno treniranje pre upotrebe rešenja.

**Metodologija**
- Istražićemo koja kombinacija metoda daje bolje rešenje
- Priprema slike: binarizacija sa adaptivnim pragom, normalizacija slike, region of interest, canny edge detector, hog
- Deep learning: konvolucioni slojevi za reprezentaciju ručnih i telesnih pokreta, potpuno povezani slojevi za mapiranje kodiranih pokreta na akcije
- Testiraćemo kako utiče držanje određenih predmeta u rukama dok korisnik rukuje volanom, npr. dva markera sa crnim poklopcem itd.
- Modul za kontrolisanje vozila
- Moduli za kontrolisanje drugih tipova igrica

**Metode evaluacije**
- Skup podataka ćemo podeliti na train, validation i test. Model će se trenirati nad train skupom. U toku treniranja vršiće se validacija modela sa validation skupom. Nakon treniranja, model će se testirati nad test skupom.
- Nakon automatskih testiranja, rešenja će se istestirati unutar određenih igara.
- Funkcija greške: categorical cross entropy
- Koristićemo matricu konfuzije da pronađemo slabe tačke modela

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by tarjantamas** [comment]
[GitHub Repozitorijum](https://github.com/tarjantamas/Virtual-Controller-CNN)
