### ISSUE TITLE
Detekcija lica na videu, prepoznavanje emocija i klasifikacija pola

### ISSUE THREAD

**Issue by DejanS24** [ftn-ai-lab/sc-2018-siit#12]
**Tim:**
Miloš Pantić, SW57/2015
Damir Hadžić, SW41/2015
Dejan Šorgić, SW31/2015

**Definicija problema**
Detekcija lica na video snimku, odredjivanje pola detektovane osobe, kao i određivanje emocija na osnovu facijalne ekspresije osobe. 

**Skup podataka:**
Kao skup podataka u projektu će se koristiti video snimci preuzeti sa interneta, sa akcentom na snimke koji sadrže veći broj ljudi, radi bolje evaluacije projekta. Za obucavanje NN kod klasifikacije emocije i pola koristiće se dataset-ovi sa slikama ljudskih lica.

**Metodologija:**
Detekcija lica na video snimcima bice realizovana putem YOLO algoritma.
Neuronske mreze za detekciju emocije i klasifikaciju pola bice obučene gore pomenutim dataset-om.
Prepoznavanje emocija će biti vršeno putem obučene CNN. Klasifikaicja pola preko obučene CNN takođe.

**Evaluacija:**
Za evaluaciju tacnosti pri detekciji lica, kao i klasifikaciji emocije i pola, koristice se ručna evaluacija preko video snimaka sa različitim brojem osoba, vreme procesiranja video snimka i Precision and Recall.

**Repozitorijum:**
https://github.com/DHadzic/SoftComputing

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
