### ISSUE TITLE
Klasifikacija instrumenata

### ISSUE THREAD

**Issue by gagi3** [ftn-ai-lab/sc-2018-siit#13]
**Tim:**
- Vladimir Gajčin, SW-49/2014

**Definicija problema:**
- Klasifikacija (prepoznavanje) instrumenata na osnovu audio zapisa.

**Motivacija rešenja:**

- Implementacija izdvajanja pojedinačnih instrumenata iz multiinstrumentalnih audio zapisa.

**Skup podataka:**
- Verovatno će se koristiti ili [IRMAS](https://www.upf.edu/web/mtg/irmas), ili [NSynth](https://magenta.tensorflow.org/datasets/nsynth) dataset. IRMAS sadrži multiinstrumentalne audio zapise, dok NSynth samo jednoinstrumentalne (ali sadrži varijacije među instrumentima - razdvaja i razlikuje akustične, električne/elektronske i sintetizovane zvukove određenih instrumenata).

**Metodologija:**
- Koristiće se Furijeova transformacija radi diskretizacije ulaznih podataka, i k-NN (k-nearest neighbour) algoritam za klasifikaciju instrumenata.

**Evaluacija:**
- Podaci su podeljeni na _train_, _validation_ i _test_ skupove. Svi podaci iz odabranog dataset-a će unapred biti označeni, između ostalog, instrumentom/instrumentima, pa ćemo to koristiti kao evaluaciju tačnosti rešenja.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by gagi3** [comment]
GitHub: https://github.com/gagi3/instrecognition-tool
