### ISSUE TITLE
Korekcija prevoda

### ISSUE THREAD

**Issue by ssrbislav** [ftn-ai-lab/sc-2018-siit#14]
**Tim**

- Bojana Ćorilić SW39/2014
- Srbislav Stojić SW83/2016

**Definicija problema**

- Prevod u filmu nije usklađen sa govorom. Imamo dva slučaja:
  - Prevod je pomeren za fiksnu vremensku razliku.
  - Prevod se tokom trajanja filma pomera za neki rastući interval (zavisi od broja frejmova po sekundi datog video materijala).

**Motivacija**

- Čest je slučaj da filmovi, koje preuzimamo sa interneta, nemaju ugrađen prevod. Pri naknadnom dodavanju prevoda, dešava se da tekst ne bude usklađen sa govorom. Stoga bi ovo predstavljalo odlično rešenje koje može da upotpuni korisnikov doživljaj pri gledanju filmova.

**Metodologija**

- FFT (Fast Fourier Transform) metod za diskretizaciju signala, kako bi se na osnovu frekvencije zvuka odredilo kada je u pitanju ljudski glas. Za proveru ispravnosti i korekciju prevoda biće korišćen Guglov softver za prepozvanje i transformaciju zvuka u tekst (Speech to Text).

**Tehnologije**

- Python
- Google Speech Recognition softver

**Podaci**

- Video materijal
- .srt fajlovi za prevod

**Evaluacija**

 - Puštanje video materijala sa .srt fajlom na kome je izvršena korekcija i provera njegove ispravnosti

**Repozitorijum**

- https://github.com/ssrbislav/Subtitle_Correction.git

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
