### ISSUE TITLE
Detekcija i očitavanje registarskih tablica

### ISSUE THREAD

**Issue by MaravicJ** [ftn-ai-lab/sc-2018-siit#15]
Tim
Jelena Maravić, SW24/2015

Definicija problema:
Detekcija registarske tablice na slici i izdvajanje karaktera sa iste.

Motivacija rešenja:
Rešenje može biti korišteno za sisteme gde je potrebno očitavanje registarskih tablica.

Metodologija:
Za diferenciranje registarske tablice od pozadine na slici biće primenjen thresholding. Treniranje konvolucione neuronske mreže biće korišteno za prepoznavanje brojeva i slova na registarskoj tablici.

Evaluacija:
Provera tačnosti očitane tablice će se vršiti upoređivanjem vrednosti iz fajla koji će sadržati stvarne vrednosti tablica.

Repozitorijum:
https://github.com/MaravicJ/LicencePlateRecognition

**Comment by vdragan1993** [comment]
Koji skup podataka planirate da koristite? Da li ćete sami skupljati podatke, ili koristiti neki od postojećih skupova podataka?
