### ISSUE TITLE
Prepoznavanje biljaka 

### ISSUE THREAD

**Issue by Pejicic** [ftn-ai-lab/sc-2018-siit#17]
**Tim:**

-  Jelena Pejičić, SW35/2015

**Definicija problema:**

-  Prepoznavanje biljaka na osnovu njihovog lista

**Motivacija problema:**

- Prepoznavanje biljaka bi imalo primjenu u praćenju i očuvanju različitih vrsta biljaka, kao i u raznim medicinskim istraživanjima

**Skup podataka:**

- Kao dataset će se najvjerovatnije koristiti već napravljeni dataset koji sadrži 32 vrste biljaka [http://flavia.sourceforge.net/](url)  ili neki sličan dataset koji se može pronaći na internetu.

**Metodologija:**

- Nad slikom će se prvo vršiti pretprocesiranje, poput pretvaranja u grayscale sliku, thresholding i slično. Nakon toga će se vršiti ekstrakcija obilježja, poslije koje bi trebalo da se zadrže relevantne informacije poput oblika i teksture listova. Kao obučavajući algoritam će se najvjerovatnije koristiti SVM.

**Evaluacija:**

- Za evaluaciju će se mjeriti tačnost odnosno accuracy prepoznavanja

**Github repozitorijum**

https://github.com/Pejicic/SoftComputing

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
