### ISSUE TITLE
Prepoznavanje puteva na satelitskim slikama gradova

### ISSUE THREAD

**Issue by lbilic** [ftn-ai-lab/sc-2018-siit#18]
**Tim:**
- Bilić Luka, SW-49/2015
- Balenović Marko SW-39/2015

**Definicija problema:**
- Prepoznavanje puteva na satelitskim slikama gradova.

**Skup podataka:**
- Ručno pravljen skup podataka korišćenjem satelitskih slika, i njihovim anotiranjem u Adobe Illustrator-u. 
- Našli smo neke već anotirane skupove, ali su oni uglavnom mali da bismo garantovali odgovarajuću preciznost koristeći samo njih.

**Metodologija:**
- Koristićemo U-Net mrežu za segmentaciju slika

**Evaluacija:**
- Podelićemo skup anotiranih slika na train, validation, i test skupove. 
- Grešku predstavlja odnos površina preseka anotiranog segmenta i predikcije, i površine predikcije.

**GitHub:**
- https://github.com/lbilic/Soft

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
