### ISSUE TITLE
Igranje Pacman-a pomoću real-time detekcije objekta na snimku

### ISSUE THREAD

**Issue by SaraPetrovic** [ftn-ai-lab/sc-2018-siit#19]
Tim:
Sara Petrović, SW60/2015

Definicija problema:
Frejmovi realtime snimka će biti podeljeni u 4 kvadranta. Potrebno je detektovati objekat na video snimku i u zavisnosti u kom kvadrantu se objekat nalazi komandovaće se kretanje pacman-a (gore,dole,levo,desno).

Metodologija:
Detektovanje objekta u šaci biće odradjeno pomoću tresholding-a. Kada je slika treshold-ovana, određuju se koordinate detektovanog objekta i na osnovu njih se određuje kom kvadrantu pripada detektovani objekat. Pomoću pyautogui biblioteke će se davati komande za kretanje pacman-u. Detektovanje objekta u šaci biće odrađeno i pomoću obučene konvolucione neuronske mreže za real-time detekciju objekata iz biblioteke OpenCV . Rezultati će biti poređeni sa gore pomenutim načinom. Za implementaciju će biti korišćen python programski jezik.

Evaluacija:
Pratiće se da li kretanje pacman-a odgovara kretanju detektovanog objekta na snimku.

**Comment by vdragan1993** [comment]
Definicija i evaluacija problema nisu najjasniji:
 - na čemu se vrši detekcija: da li se korsti postojeći Pacman GUI ili će se kreirati novi?
 - koji objekat se detektuje?

**Comment by SaraPetrovic** [comment]
Koristice se postojeci Pacman GUI, najverovatnije iz biblioteke pygame.
Na osnovu pomeranja sake, u kojoj se nalazi zeljenji predmet (npr. loptica), detektuje se u kom se od cetiri kvadranta frejma nalazi izabrani predmet i time se odredjuje smer kretanja pacmana (gore, dole, levo, desno).

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by SaraPetrovic** [comment]
Repozitorijum: https://github.com/SaraPetrovic/Soft
