### ISSUE TITLE
Pedestrian Detection 

### ISSUE THREAD

**Issue by VukVladisavljevic** [ftn-ai-lab/sc-2018-siit#2]
### **Tim**
Ognjen Vladisavljević SW38/2015
Vuk Vladisavljević SW59/2014

### **Definicija problema**
Detekcija i praćenje osoba na video snimku.

### **Motivacija problema**
Uspešno rešenje se može iskoristiti za poboljšanje bezbednosti na putevima i javnim mestima tako što će izdvojiti osobe i olakšati praćenje njihovog kretanja. 

### **Skup podataka**
Kao skup podataka će se koristiti video snimci video nadzora na javnim mestima ili auto kamera.

### **Metodologija** 
Prvi korak predstavlja konverzije ulaznih snimaka u odgovarajući format. Nakon inicijalne konverzije, sama detekcija će se obaviti korišćenjem Histograma objektnih gradijenata(HOG) za izdvajanje deskriptora i linearnog klasifikatora za prepoznavanje željenih/neželjenih osobina objekta koji je u ovom slučaju osoba. Non-Maximum Suppression će biti korišćen u slučaju prekomernih okvira koji če biti pretvoreni u jedinstveni okvir za svaku identifikovani osobu.

### **Evaluacija**
Validacija rešenja će se vršiti na osnovu test skupa sa video klipova.

Git repozitorijum: https://github.com/ognjenVlad/SC2018

**Comment by vdragan1993** [comment]
Koju meru/mere performansi planirate da koristite prilikom evaluacije?

**Comment by VukVladisavljevic** [comment]
Broj prepoznatih pešaka i poređenje različitih snimaka i efikasnosti algoritma za svaki od njih.

**Comment by vdragan1993** [comment]
Kojom metrikom/metrikama planirate da merite efikasnost algoritma?

**Comment by VukVladisavljevic** [comment]
Pored manuelnih testova, koristili bismo mere tačnosti(Accuracy) ili Precision and Recall

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
