### ISSUE TITLE
Računanje kalorija hrane na osnovu slike

### ISSUE THREAD

**Issue by losaodluka01** [ftn-ai-lab/sc-2018-siit#20]
**Tim**
1. Mihajlo Jovković, SW10/2015
2. Katarina Radišić, SW21/2015
3. Jelena Drča, SW23/2015

**Definicija problema**

Problem koji ćemo rešavati je računanje kalorija hrane na osnovu slike. Cilj je da se sa slike hrane prepoznaju svi tipovi hrane, oceni njihova gramaža i na osnovu toga izračuna konačna kalorijska vrednost obroka sa slike.

**Motivacija**

U današnje vreme ljudi sve više pažnje pridaju fizičkom izgledu. Dok neki pokušavaju da smršaju drugi pak žele da povećaju mišičnu masu. Šta god bio vaš cilj jedno je sigurno - neophodno je da znate unesenu količinu kalorija. Ako ste ikada pokušali da pratite unos kalorija, znate koliko to može biti naporan proces. Smatramo da bi korišćenje našeg softvera učinilo proces fizičke transformacije ne samo jednostavnijim već i zabavnim.

**Skup podataka**

Kao skup podataka u projektu će se koristiti slike preuzete sa interneta koje će sadržati slike individualne hrane, jednostavnih obroka, kao i komplikovanijih porcija u kojima je hrana pomešana. Na slikama će se pored porcije hrane naći i objekat koji će nam služiti kao skala za procenu stvarne količine hrane.

**Metodologija**

Prvo ćemo jednostavnim transformacijama standardizovati format slike kako bi imali tačnije rezultate segmentacije. Nakon toga koristimo segmentaciju na osnovu boje i texture kao i k-means clustering. Klasifikaciju hrane vršimo preko konvolutivne neuronske mreže koja je prethodno obučena na gore pomenutom dataset-u. Količinu hrane određujemo skaliranjem u odnosu na dati objekat sa slike ( npr.: tanjir, prst, olovka... ). Za kraj nam samo ostaje da izračunamo ukupnu kalorijsku sumu na osnovu procenjene količine svakog tipa hrane u porciji.

**Evaluacija**

Skup podataka biće podeljen na train, validation i test skup. Train skup koristimo za obučavanje naše neuronske mreže, validacioni skup za dalje podešavanje parametara tokom razvoja dok test skup koristimo za konačnu procenu kvaliteta. Po potrebi će se koristiti i ručna evaluacija.

**Comment by vdragan1993** [comment]
Koju metriku planirate da koristite za procenu kvaliteta (tačnost ili neka greška (npr. neka od ovih: https://www.kaggle.com/learn-forum/52081))?

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Kendra1** [comment]
https://github.com/Kendra1/Food-recognition-and-calorie-counter
