### ISSUE TITLE
Prepoznavanje ručno pisanog kurzivnog ćiriličnog teksta sa slike

### ISSUE THREAD

**Issue by lazarmarkovic** [ftn-ai-lab/sc-2018-siit#24]
**Tim**
Lazar Marković, SW56/2015

**Definicija problema**
Prepoznavanje ručno pisanog ćiriličnog teksta sa slike napisanog kurzivnim stilom, što podrazumeva da su sva slova u datoj reči spojena.

**Motivacija**
Potencijalno dobijanje super-mega-moći da pročitam sopstveni "rukopis". :sunrise_over_mountains:

**Skup podataka**
Skup podataka bih sam pravio na sledeći način:

-  Više ljudi bi napisalo kurzivni (pisani) ćirilični alfabet (mala i velika slova) na datim papirima gde je svako slovo odvojeno razmakom
- Napravio bih fotografije papira i odradio izdvajanje regiona u kojima se nalaze slova i sačuvao ih kao zasebne fajlove
- Svaka slika bi bila anotirana slovom alfabeta koje se na njoj nalazi
- Za potvrdu i eventualnu korekciju prepoznate reči koristiću skup reči našeg jezika: https://github.com/grakic/hunspell-sr/

**Metodologija**

- Koristio bih thresholding za izdvajanje slike papira iz cele slike
- Detekcija reči na papiru pomoću Sobela i K-means algoritma
- Segmentacija regiona reči u regione slova pomoću Projection Histogram-a recimo
- Klasifikacija izdvojenih karaktera 
- Približno pronalaženje reči u rečniku (Levenshtein distance) radi potvrde ili korekcije reči

**Evaluacija**
Merim accuracy (correct/N) za:

- Sva slova u datom primeru
- Za sve reči u datom primeru pre korekcije (reč je ispravna ako su sva slova u njoj ispravna)
- Za sve reči u datom primeru posle korekcije

**Repozitorijum:** https://github.com/lazarmarkovic/cursive-cyrillic-htr

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
