### ISSUE TITLE
Detekcija i zamena lica na videu

### ISSUE THREAD

**Issue by spsjvc** [ftn-ai-lab/sc-2018-siit#25]
**Tim**
* Mladen Grujičić, SW-28/2015
* Dragiša Spasojević, SW-50/2015

**Definicija problema**
* Obrada živog prenosa video snimka sa web kamere, detekcija lica (i pojedinačnih karakteristika lica) i zamena dva detektovana lica.

**Skup podataka**
* Za demonstraciju rešenja biće korišćen živi prenos video snimka sa web kamere sa različitim brojem osoba i u različitim uslovima.

**Metodologija**

- Detekcija lica uz korišćenje OpenCV i HAAR kaskadnog klasifikatora.
- Detekcija 68 tačaka lica uz pomoć dlib biblioteke.
- Zamena lica, korekcija boja.

**Evaluacija**
* Evaluacija rešenja biće vršena empirijski. 

**GitHub repozitorijum**
* https://github.com/spsjvc/face-swapper

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
