### ISSUE TITLE
Prepoznavanje proizvođača, vrste i vrste napajanja alata

### ISSUE THREAD

**Issue by n-stajic** [ftn-ai-lab/sc-2018-siit#26]
Tim
    Stevan Jankulov SW48/2018
    Nikola Stajić SW44/2015

Definicija problema
    Prepoznavanje ručnog električnog alata sa slike, odnosno prepoznavanje koji je alat u pitanju, ko je proizvođač alata i da li je alat sa slike na akumulatorsko napajanje ili na struju. Rezultate bi koristili za internet pretragu po vrsti alata, proizvođaču i vrsti napajanja.

Skup podataka
    Skup podataka bi sami pravili tako što bi slikali razne alate i skidali slike sa sajtova za prodaju alata, a zatim bi ih ručno obeležavali.

Metodologije
    U predprocesiranju bi radili izdvajanje mašine od pozadine segmentacijom slike pomoći lokalnog praga, uz kombinaciju sa dilacijom i erozijom radi uklanjanja šuma. Za prepoznavanje alata sa slike bi koristili konvolutivne neuronske mreže. Pošto se na alatu često nalazi i ime proizvođača koristili bi tensorflow framework ili neku sličnu biblioteku za prepoznavanje teksta.

Evaluacija
    Skup podataka bi podelili na trening, validacioni i test skup. Merili bi kolika je tačnost pogotka sva tri parametra, odnosno vrste alate, proizvođača alata i vrste napajanja alata.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by n-stajic** [comment]
https://github.com/JankulovS/softcomputing-powertools
