### ISSUE TITLE
Prepoznavanje i resavanje jednostavnih matematickih izraza

### ISSUE THREAD

**Issue by marinagjerkovic** [ftn-ai-lab/sc-2018-siit#27]
**Tim**
- Marina Jerkovic, sw25/2015
- Ilija Malinovic, sw46/2015

**Definicija problema**
Prepoznavanje i resavanje rucno pisanih jednostavnih matematickih zadataka sa slike. U pitanju ce biti operacije sabiranje, oduzimanje, mnozenje, deljenje, stepenovanje, korenovanje. Takodje ce biti moguce i grupisanje u zagrade, kao i razlomci.

**Motivacija**
Dobijanje resenja jednostavnih izraza bez upotrebe kalkulatora.

**Skup podataka**
Skup podataka bismo napravili sami - razlicitim rukopisom pisani na papiru i uslikani iz razlicitih uglova pod razlicitim osvetljenjem potrebni znakovi kao i matematicki izrazi.

**Metodologija**
- tresholding za izdvajanje papira sa slike
- detekcija regiona od interesa unutar izraza
- detekcija znakova unutar tih regiona - konvoluciona neuronska mreza
- resavanje izraza

**Evaluacija**
Resenje bismo evaluirali proverom tacnosti prepoznatih znakova kao i tacnosti izracunatih izraza.

**Comment by vdragan1993** [comment]
Ovaj projekat može da radi najviše jedna osoba, i to u slučaju da se problem proširi:
 - razlomcima
 - barem još jednom operacijom (npr. korenovanje)
 - slikama izraza iz raznih uglova i pod različitim osvetljenjem. 

Takođe, opis metodologije nije zadovoljavajući.
