### ISSUE TITLE
Pretrazivanje slicnih filmova

### ISSUE THREAD

**Issue by ikijaem** [ftn-ai-lab/sc-2018-siit#29]
Tim

Marina Jerkovic, sw25/2015
Ilija Malinovic, sw46/2015

Definicija problema
Preporuka slicnih filmova na osnovu jednog izabranog. Moguce koristiti prilikom trazenja filma, pravljenja kolekcija, brze pretrage....

Motivacija
Pretrazivanje filmova iz baze koji su slicni odabranom

Skup podataka
Najvjerovatnije ce se koristiti skupovi podataka sa sajta MovieLens.

Metodologija
Za filtriranje cemo najvjerovatnije da korisimo content-based filtering.

Evaluacija
Vrsice se empirijski, na osnovu poznavanja filma od strane clanova tima.

**Comment by vdragan1993** [comment]
Pošto vas je dvoje u timu, preporuka da pored content-based implementirate i collaborative filtering.

Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by ikijaem** [comment]
https://github.com/ikijaem/IlijaMarinaDataBase
