### ISSUE TITLE
Detektovanje pneumonie na rendgenskim snimcima pluća

### ISSUE THREAD

**Issue by IgorMaj** [ftn-ai-lab/sc-2018-siit#3]
**Tim**
Igor Majić SW59/2015

**Definicija problema**

Klasifikovanje rendgenskih snimaka pluća po tome da li se na njima nalazi virusna ili bakterijska pneumonia,  odnosno normalan nalaz. 

**Motivacija**

Usled globalnog nedostatka radiologa, često su lekari drugih specijalnosti prinuđeni da tumače rendgenske snimke. Zbog toga se povećava procenat pogrešno postavljenih dijagnoza.  Dobro obučen model bi mogao delimično da zameni eksperte, koji bi onda imali vremena da se posvete komplikovanijim slučajevima. 

**Skup podataka**

Skup podataka koji će se koristiti nalazi se na sledećem [linku](https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia).  Već je  podeljen na obučavajući, validacioni i test skup. 

**Metodologija**

Prvi korak će predstavljati pretprocesiranje slika koje će prvo biti svedene na fiksnu veličinu (pošto su jako visoke rezolucije i nejednakih veličina), zatim normalizovane po pikselima.  Koristiće se konvolutivna neuronska mreža za klasifikaciju snimaka na neku od tri kategorije (nema pneumonie, bakterijska pneumonia i virusna pneumonia). Tačna arhitektura mreže će biti naknadno određena, iako će pored konvolutivnih i potpuno povezanog sloja na kraju najverovatnije sadržati i max pooling slojeve. Kao aktivaciona funkcija će se koristiti ReLU. 

**Evaluacija**

Za evaluaciju će se pored klasične preciznosti, računati i matrica konfuzije, koja će dati verniju sliku o tome koje kategorije ovaj model pogrešno klasifikuje. 

**Repozitorijum**
https://github.com/IgorMaj/DetectingPneumonia

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
