### ISSUE TITLE
Detekcija stanja table za igricu "Connect 4"

### ISSUE THREAD

**Issue by elenaroncevic** [ftn-ai-lab/sc-2018-siit#37]
### Tim
Elena Rončević sw7-2015

### Definicija problema
Potrebno je raspoznati žetone dva različita igrača i na osnovu broja žetona svakog igrača odrediti koji je na potezu i najpovoljniji potez koji bi mogao da odigra. Takođe treba se prepoznati kraj igre i u tom slučaju odrediti pobednik

### Skup podataka
Fotografije će biti prikupljene pomoću lične kamere i sa interneta

### Metodologije
Uz pomoć OpenCV biblioteke (primenom thresholda i korišćenjem HSV palete boje):
- Detektovanje ivice table i njenih dimenzija
- Detekcija žetona dve različite boje i praznih polja na osnovu boje
- Uz pomoć dimenzije table i poznatog broja redova i kolona detekcija pozicije žetona i praznih mesta

Korišćenjem MiniMax algoritma:
- Nakon detekcije pozicije žetona kreiranje matrice igre odnosno table
- Na osnovu matrice igre uz pomoć minimax algoritma odrediće se najpovoljniji sledeći potez

### Mogući problemi
Iskrivljenost table i pozadina bi mogli uticati na preciznost prepoznavanja 

### Evaluacija
Proveravaće se da li je prepoznat dobar broj žetona svakog igrača i da li je stanje ispravno prepoznato. 

### Repozitorijum
https://github.com/elenaroncevic/connectFour

**Comment by vdragan1993** [comment]
Kratak nacrt metodologije nije zadovoljavajući.
U naredna 24 sata, ili dopunite metodologiju, ili prijavite predefinisani projekat.

**Comment by elenaroncevic** [comment]
Dopunjena je metodologija, nadam se da je ovo dovoljno.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
