### ISSUE TITLE
Rešavanje Mica igre na osnovu učitane fotografije table sa figurama.

### ISSUE THREAD

**Issue by jovosunjka** [ftn-ai-lab/sc-2018-siit#4]
<b>Tim</b> 
SW26/2015 Jovana Jovanović
SW17/2015 Jovo Šunjka

<b>Definicija problema</b>
&emsp;Rešavanje Mica igre na osnovu učitane fotografije, uz korišćenje dva već implementirana algoritma na ORI-ju (minimax, reinforcement learning) i deep reinforcement learning (tek treba da bude implementiran). 
&emsp;Mica je igra koju igraju dva igrača i sastoji se iz tri faze. Tabla se sastoji od mreže sa 24 tačke. Svaki igrač ima 9 figura, koje su obično crno-bele. Igrači pokušavaju da formiraju micu, odnosno tri sopstvene figure spojene horizontalno ili vertikalno. Kada se sklopi mica igraču je dozvoljeno da ukloni jednu protivničku figuru. Igrač pobeđuje kada protivnika svede na 2 figure ili kada ga dovede u poziciju da ne može da pomeri nijednu figuru. Igra započinje prvom fazom u kojoj igrači postavljaju figure na prazne tačke. Kada se postave sve figure, počinje druga faza igre u kojoj igrači naizmenično pomeraju figure na susedne slobodne tačke i pokušavaju da formiraju micu. Kada jedan od igrča ostane sa 3 figure, počinje treća faza, gde je igraču koji je ostao sa 3 figure dozvoljeno da skače na slobodne tačke.

<b>Skup podataka</b>  
&emsp;Za skup podataka će se koristi fotografije table sa figurama koje ćemo mi napraviti, slikajući iz različitih uglova. 
 
<b>Metodologija</b>
1. Priprema date slike: skaliranje i binarizacija
2. Detekcija table i izdvajanje prostora za dalju analizu
3. Detekcija postavljenih i nepostavljenih (ako nisu sve postavljene) figura i njihovo mapiranje na stanje 
   igre, na osnovu kojeg ce botovi ili čovek nastaviti da igraju
4. Izbor botova koji će da igraju jedan protiv drugog. botovi su implementirani pomoću minimax, 
   reinforcement learninig i deep reinforcement learninig
5. Botovi implementirani sa različitim algoritmima igraju jedan protiv drugog dok ne dodjemo do kraja 
    igre

<b>Metode evaluacije</b>
&emsp;Prvo ćemo proveravati da li su figure dobro prepoznate i mapirane, tj. da li je figura sa odgovarajućom bojom na odgovarajućoj poziciji, na tabli. Na kraju, ćemo izmeriti performanse algoritama koji su bili upotrebljeni na osnovu broja poteza koji su agenti odgirali i vremena potrebnog da se odigra partija. 

<b>Repozitorijum</b>
<a target="_blank" href="https://github.com/jovosunjka/MicaIgraObradaSlike">https://github.com/jovosunjka/MicaIgraObradaSlike</a>

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
