### ISSUE TITLE
Detekcija lica na videu i dodavanje Snapchat filtera

### ISSUE THREAD

**Issue by ivanovicb** [ftn-ai-lab/sc-2018-siit#5]
**- Tim:**
Bojana Ivanović, SW5/2015
Vanja Mijatov, SW13/2015

**- Definicija problema:**
Obrada video snimaka, detekcija lica i delova lica (oči, usta...) osoba na slici i dodavanje Snapchat filtera na detektovane delove lica.

**- Skup podataka:**
U projektu će se za evaluaciju i demonstraciju programskog rešenja koristiti video snimci preuzeti sa interneta i to različiti tipovi kao npr. snimak sa jednom osobom, sa više osoba, video snimci sa različitim osvetljenjem, različitog kvaliteta...

**- Metodologija:**
1. Učitavanje video snimka i izdvajanje frejmova koji se po potrebi obrađuju
2. Detekcija lica na frejmovima i delova tog/tih lica (korišćenjem dlib biblioteke (HOG+SVM algoritam i detekcija 68 značajnih tačaka na licu) i opencv biblioteke(HAAR kaskadni klasifikator))
3. Dodavanje izabranog filtera (sličice) na prepoznati region

**- Evaluacija**
Prvo se proverava uspešnost algoritama pri detektovanju odgovarajućeg broja lica. Zatim, određuje se da li je filter (sličica) pozicionirana na odgovarajući region (IoU - Intersection over Union). Upoređuje se uspešnost ranije navedenih algoritama (preciznost i vreme procesuiranja video snimka).

Link ka GitHub repozitorijumu: https://github.com/Vanja-Mijatov/Face-Snap.git

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by ivanovicb** [comment]
Link ka GitHub repozitorijumu (prethodno update-ovan issue, link dodat i tamo):
https://github.com/Vanja-Mijatov/Face-Snap.git
