### ISSUE TITLE
Chess recognition

### ISSUE THREAD

**Issue by adamovivan** [ftn-ai-lab/sc-2018-siit#6]
**Tim**
- Adamov Ivan, SW19/2015

**Definicija problema**
Treba uslikati šahovsku tablu i odrediti položaj figura na istoj, zatim to povezati sa nekim šahovskim programom radi bolje vizualizacije.

Problem se može podeliti na dva podproblema:
1. Prepoznavanje šahovske table sa slike: veličina, orijentacija, boja polja
2. Prepoznavanje šahovslih figura: problem detekcije, lokalizacije i identifikacije

**Metodologija**
1. Problem table
Za detekciju ivica će biti korišćen Canny, za detekciju linija između polja Hough Transform.
2. Problem figura
Za prepoznavanje figura će se koristiti SIFT, HOG i SVM, kasnije možda bude ubačen i R-CNN. 

**Evaluacija**
Za evaluaciju prepoznavanja table i figura biće koriščena matrica konfuzije.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by adamovivan** [comment]
https://github.com/adamovivan/chess-recognition
