### ISSUE TITLE
Night sight

### ISSUE THREAD

**Issue by motomaniac96** [ftn-ai-lab/sc-2018-siit#7]
### Tim
Nikola Tomic, SW/45-2015

### Definicija problema
Sum kod slika je verovatno najveci problem bilo kog sistema koji se oslanja na sliku ili video. Medjutim postoji velika razlika i problem kod slika/videa u uslovima (izuzetno) slabog osvetljenja. Povecanjem ISO vrednosti dobijamo vise svetla na ulazu, ali u isto vreme pojacavamo sum. 

### Skup podataka
Koriscen je dataset slika Sony DSLR kamere gde su iste slike slikane sa razlicitim ISO vrednostima [link](https://drive.google.com/open?id=1G6VruemZtpOyHjOC5N8Ww3ftVXOydSXx) (25GB).

### Metodologija
Problem se moze resiti koriscenjem trenirane konvolucione mreze nad navedenim dataset-om i kombinacijom metoda za: filtriranje suma (B3MD), gama korekcije, low-light enhancement tehinika, kategorizacija piksela, izostravanjem, podesavanjem white balansa i mnoge druge.

Neke od gore navedenih metoda ce biti koriscene u zavisnosti od performansi pri izvrsavanju i treniranju kao i rezultata.

### Evaluacija
Za evaluaciju slike se moze koristiti Peak Signal-to-Noise Ratio (PSNR) i/ili Structural SIMilarity (SSIM) metoda jer postoji referentni skup "idealnih" slika [link](https://drive.google.com/file/d/1wfkWVkauAsGvXtDJWX0IFDuDl5ozz2PM/view?usp=sharing) (12GB).

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by motomaniac96** [comment]
Hvala !
