### ISSUE TITLE
Detekcija i rešavanje sudoku puzle

### ISSUE THREAD

**Issue by simsimkic** [ftn-ai-lab/sc-2018-siit#8]
**Tim**
Simona Prokić, SW16/2015

**Definicija problema**
Rešavanje sudoku puzle na osnovu učitane fotografije. 

**Skup podataka**
Za skup podataka koristiće se MNIST baza ručno pisanih cifara i fotografije sudoku puzli različitog osvetljenja i jasnoće.

**Metodologija**
- priprema slike: binarizacija, primena thresholdinga,...
- detekcija ivica i grida puzle
- detekcija brojeva unutar puzle
- rešavanje sudoku puzle pomoću genetskog algoritma i backtracking algoritma
- prikaz i analiza rešenja i primenjenih algoritama za rešavanje

**Evaluacija**
Prilikom evaluacije rešenja će se prvo proveravati da li su sve cifre pravilno prepoznate, a zatim se proverava da li je rešenje sudoku puzle ispravno.

Repozitorijum: [https://github.com/simsimkic/sudoku-solver](url)

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
