### ISSUE TITLE
Autonomno vozilo

### ISSUE THREAD

**Issue by itacca** [ftn-ai-lab/sc-2018-siit#9]
**Tim:**
- Filip Baturan @FilipBaturan, SW 9/2015
- Igor Tica @itacca , SW14/2015
- Filip Basara @filipbasara0, SW36/2015
- Aleksandar Varga @aleksandar-varga,     SW40/2015

**Motivacija:**
- Nadmašiti [Teslu](https://www.tesla.com/) u svim aspektima autonomne vožnje.

**Definicija problema:** 
- Identifikacija i implementacija modula neophodnih za kretanje vozila u simulatoru bez ljudske intervencije. 
- Moduli: 
     - detekcija pešaka
     - detekcija automobila
     - detekcija semafora
     - detekcija linija na putu
     - modul za upravljanje 
- Modul za upravljanje koristi izlaze ostalih modula i donosi odluke o kretanju automobila u simulatoru.

**Skup podataka:**
 
- Za svaki modul se koristi poseban dataset, koji se sastoji od anotiranih slika preuzetih sa interneta. 
- Datesetovi po modulima su: 
   1. za detekciju pešaka: [CALTECH](http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/)
   2. za detekciju automobila: [KITTI](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d)
   3. za detekciju semafora: [LISA traffic lights](http://cvrr.ucsd.edu/vivachallenge/index.php/traffic-light/traffic-light-detection/)
   4. za detekciju linija na putu: [PASCAL VOC 2012](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/?fbclid=IwAR1nQ3P_tajbd39TBFFw06aOoPs4JX1iVd0hkbw7ST75jFxEKj4Adaws_Do), [CULane](https://xingangpan.github.io/projects/CULane.html?fbclid=IwAR3kPJXmt5tzV-bcRlw19VGXQqdpJwQGJ7uirzitC-q9NmTaJNjBGi_tv50)

**Metodologija:**
- Moduli za detekciju pešaka, automobila i semafora su zasnovani na _Single shot detection_ modelima ili na modelima koji posebno rade lokalizaciju i klasifikaciju. Modul za detekciju linija će segmentisati sliku korišćenjem _encoder-decoder CNN_ arhitekture.
- Modul za upravljanje će dobijati _feature_ vektore od pojedinačnih modula, kombinovati u jedan i korišćenjem evolutivnih algoritama ili _reinforcement learninga_  će upravljati automobilom.  

**Evaluacija:**
- Pojedinačni moduli će se evaluirati na osnovu slika dobijenih iz simulatora korišćenjem _mAP_ i _mean intersection over union_ metoda, dok će se upravljački modul evaluirati na osnovu _benchmark_-a sastavljenog u simulatoru. Analiziraće se podaci dobijeni tokom vožnje u simulatoru tokom trajanja testa.

**GitHub repozitorijum:**
- [Affinis lab](https://github.com/affinis-lab)

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
